trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    export branchname=`echo "$(Build.SourceBranch)" | cut -c 12-`
    git checkout $branchname
    git pull
  displayName: 'Full checkout of current branch'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

# May want to run full test suite?

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email ""
      git config --global user.name "DevOps Pipeline"
  displayName: "Setup git pipeline configuration"

- script: |
    npm version $(RELEASETYPE)
  displayName: 'Bump version number'

- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: 'f9bc0907-731b-4968-8b3a-f3475b0970ef'
  displayName: "Publish package to JOSIE Artifacts"

- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '08c311fe-7825-4aab-9b83-b903d9e00640/42335431-f3e9-43c3-a6a5-6088140dd368'
  displayName: "Publish package to Azure Artifacts"

- script: |
    git push -q https://$(GITHUBPAT)@github.com/CybercentreCanada/Angular-QueryBuilder.git
  displayName: 'Push changes to version number'