# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git checkout $(Build.SourceBranch)
    git pull
  displayName: 'Get git stuff'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email ""
      git config --global user.name "DevOps Pipeline"

- script: |
    git status
  displayName: 'Get git stuff'

- script: |
    npm version $(RELEASETYPE)
  displayName: 'Bump version number'

- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '08c311fe-7825-4aab-9b83-b903d9e00640/42335431-f3e9-43c3-a6a5-6088140dd368'
  displayName: "Publish package to Azure Artifacts"

- script: |
    git push
  displayName: 'Push changes to version number'